name: Publish
on:
  push:
    branches: [ main ]
  release:
    types: # This configuration does not affect the page_build event above
      - created
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Publish a Python distribution to PyPI
      uses: ortega2247/pypi-upload-action@master
      with:
        user: __token__
        password: ${{ secrets.PIP_TOKEN }}
